### ISSUE TITLE
Add GC/MS kind example

### ISSUE THREAD

**Issue by lpatiny** [mljs/nGMCA#5]
@jobo322  Could you add an example in the readme that is something like the following ?

We have as data the following matrix, on the horizontal axis the time and on the vertical axis the mass

```
0 0 1 1 1
0 0 1 1 1
2 2 2 0 0
2 2 2 0 0
```

We know that we have 2 components

Could you give an example that would give the intensity of both component as well as the pure components ?

Pure component 1 should be `1 1 0 0` and component 2: `0 0 1 1`

And I guess we should have a matrix that display the amount of the component depending the time

```
2 2 2 0 0
0 0 1 1 1
```

**Comment by jobo322** [comment]
It's done in [c0980a6](https://github.com/mljs/nGMCA/pull/3/commits/c0980a68ef85acef7b77f25b8fc66047ee04379e)

**Comment by lpatiny** [comment]
Please add also this specific example in the readme (one more example then)

**Comment by lpatiny** [comment]
Please also add this specific example
